image: node:latest

before_script:
  - node -v
  - npm -v
  - npm install

stages:
  - deploy

pages:
  stage: deploy
  script:
    - npm run build
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - master